service: serverless-ephemeral-tensorflow

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.main

plugins:
  - serverless-ephemeral

package:
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - .ephemeral/**