service: serverless-ephemeral-tensorflow

plugins:
  - serverless-ephemeral

package:
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - .ephemeral/**
    - magpie-packager/**

custom:
  ephemeral:
    libraries:
      - packager:
        compose: docker/docker-compose.yml
        service: magpie
        output: /tmp/libs/text-classification.zip
      directory: text-classification

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.main

